### ISSUE TITLE
[Flaw] Improve horizontal progress bar proportions and reduce numbers font-size.

### ISSUE THREAD

**Issue by Palloxin** [Palloxin/Lnreader-beta-Issues#18]
beta:
![image](https://github.com/Palloxin/Lnreader-beta-Issues/assets/75091899/4ff5f54c-5dd8-4e0a-9e73-c213c1b24b8d)

Stable:
![image](https://github.com/Palloxin/Lnreader-beta-Issues/assets/75091899/0c666709-fecd-44fc-9b97-12a74cf564a0)

Addition:
After using CSS to locally improve it I noticed this:

CSS used:
```css
#ToolWrapper.horizontal > #ScrollBar{
    width: 95.5vw;
}
#ToolWrapper > #ScrollBar {
    margin-top: 8px;
    width: 2.4rem;
    height: 45vh;
    min-height: 200px;
    font-size: 14px;
}
```
changed: ``width: 95.5``, ``font-size: 14``

differences:
![image](https://github.com/Palloxin/Lnreader-beta-Issues/assets/75091899/6bf7926a-af89-4dcb-be4a-be1420028ff8)
![image](https://github.com/Palloxin/Lnreader-beta-Issues/assets/75091899/f92ee286-baab-4407-ab32-f6b1dd1b3c62)
